# Capstone 2: EmporiUm Data Analysis

- **Region:** Northeast  
    - **Sales Territory 1:** Florida  
        - **Manager:** Lana Ilana  
    - **Sales Territory 2:** South Carolina  
        - **Manager:** Len Jensen  

"insert project description"

In [ ]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Customer List

In [156]:
clist = pd.read_csv('customer_list.csv')
clist.info()
clist.head()

<class 'pandas.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 1 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   cust_id|date|time|name|email|phone|sms-opt-out   521 non-null    str
dtypes: str(1)
memory usage: 4.2 KB

     cust_id|date|time|name|email|phone|sms-opt-out
0  1|2023-03-15|08:45:12|Rachel|rachel@centralper...
1  2|2023-05-22|12:30:45|R. Geller|rossg@centralp...
2  3|2023-07-09|18:15:27|Monica Geller|chefmonica...
3  4|2023-09-01|21:05:33|Chandler Bing|chandlerb@...
4  5|2023-11-18|14:22:10|Joey|howyoudoing@central...

Product Categories

In [157]:
pcategories = pd.read_csv('ProductCategories.csv')
pcategories.info()
pcategories.head()

<class 'pandas.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CategoryID     52 non-null     int64
 1   Category       52 non-null     str
 2   SubcategoryID  52 non-null     str
 3   Subcategory    52 non-null     str
dtypes: int64(1), str(3)
memory usage: 1.8 KB

   CategoryID                  Category SubcategoryID           Subcategory
0         120  Technology & Accessories       120-tab               Tablets
1         120  Technology & Accessories       120-cal           Calculators
2         120  Technology & Accessories       120-sof     Software Download
3         120  Technology & Accessories       120-hea            Headphones
4         120  Technology & Accessories       120-ext  External Accessories

Products

In [158]:
p = pd.read_csv('Products.csv')
p.info()
p.head()

<class 'pandas.DataFrame'>
RangeIndex: 669 entries, 0 to 668
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Prod Num       669 non-null    str
 1   Product        669 non-null    str
 2   CategoryID     669 non-null    int64
 3   SubcategoryID  669 non-null    str
dtypes: int64(1), str(3)
memory usage: 21.0 KB

    Prod Num                        Product  CategoryID SubcategoryID
0  105248-IT               TCL NXTPAPER 10s         120       120-tab
1  105249-IT  Dell Latitude 7320 Detachable         120       120-tab
2  105250-IT                     Realme Pad         120       120-tab
3  105251-IT             Lenovo Tab P12 Pro         120       120-tab
4  105252-IT        Microsoft Surface Pro 9         120       120-tab

Store Detail

In [159]:
sdetail = pd.read_csv('StoreDetail.csv')
sdetail.info()
sdetail.head()

<class 'pandas.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Store Location     111 non-null    str
 1   State              111 non-null    str
 2   Store ID           111 non-null    int64
 3   Territory Manager  111 non-null    str
 4   Region             111 non-null    str
 5   Region Director    111 non-null    str
dtypes: int64(1), str(5)
memory usage: 5.3 KB

  Store Location     State  Store ID Territory Manager Region  Region Director
0         Aurora  Colorado       701          Jim Heck   West  Cassie Chambers
1       Berthoud  Colorado       702          Jim Heck   West  Cassie Chambers
2        Boulder  Colorado       703          Jim Heck   West  Cassie Chambers
3    Castle Rock  Colorado       704          Jim Heck   West  Cassie Chambers
4         Denver  Colorado       705          Jim Heck   West  Cassie Chambers

Store Sales

In [160]:
ssales = pd.read_csv('StoreSales.csv')
ssales.info()
ssales.head()

<class 'pandas.DataFrame'>
RangeIndex: 335129 entries, 0 to 335128
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction Date  335129 non-null  str
 1   Store ID          335129 non-null  int64
 2   RewardsID         34943 non-null   float64
 3   Prod Num          335129 non-null  str
 4   Sale Amount       335129 non-null  float64
dtypes: float64(2), int64(1), str(2)
memory usage: 12.8 MB

  Transaction Date  Store ID  RewardsID  Prod Num  Sale Amount
0         1/1/2022       702        NaN  105349-M         8.00
1         1/1/2022       704        NaN  105350-T       144.00
2         1/1/2022       705        NaN  105351-M        44.00
3         1/1/2022       705        NaN  105352-M        47.61
4         1/1/2022       705        NaN  105353-A        20.36

## Core Marketing Analysis

### Territory managers, store IDs, and cities for stores

- Florida Store IDs:        719 - 729  
- South Carolina Store IDs: 852 - 853

In [161]:
# Create dataframe for Florida stores
fl_stores = sdetail[sdetail['State'] == 'Florida']
fl_ids = fl_stores["Store ID"].tolist()
fl_stores.rename(columns={'Store Location': 'City'}, inplace=True)

fl_stores

,City,State,Store ID,Territory Manager,Region,Region Director
26,Cape Canaveral,Florida,719,Lana Ilana,South,Andy Gisselquist
27,Fort Lauderdale,Florida,720,Lana Ilana,South,Andy Gisselquist
28,Jacksonville,Florida,721,Lana Ilana,South,Andy Gisselquist
29,Key West,Florida,722,Lana Ilana,South,Andy Gisselquist
30,Lakeland,Florida,723,Lana Ilana,South,Andy Gisselquist
31,Miami,Florida,724,Lana Ilana,South,Andy Gisselquist
32,Naples,Florida,725,Lana Ilana,South,Andy Gisselquist
33,Orlando,Florida,726,Lana Ilana,South,Andy Gisselquist
34,Sebring,Florida,727,Lana Ilana,South,Andy Gisselquist
35,Tallahassee,Florida,728,Lana Ilana,South,Andy Gisselquist
36,Tampa,Florida,729,Lana Ilana,South,Andy Gisselquist

In [162]:
# Create dataframe for South Carolina stores
sc_stores = sdetail[sdetail['State'] == 'South Carolina']
sc_ids = sc_stores["Store ID"].tolist() 
sc_stores.rename(columns={'Store Location': 'City'}, inplace=True)

sc_stores

,City,State,Store ID,Territory Manager,Region,Region Director
98,Charleston,South Carolina,852,Len Jensen,South,Andy Gisselquist
99,Greenville,South Carolina,853,Len Jensen,South,Andy Gisselquist

### Monthly revenue for in-store sales for the two sales territories, covering full period

Florida Monthly Revenue:

In [163]:
fl_sales = ssales[ssales['Store ID'].isin(fl_ids)]                                                  # Use isin to filter store sales from previous South Carolina stores dataframe

fl_sales['Transaction Date'] = pd.to_datetime(fl_sales['Transaction Date'])                         # Convert Transaction Date to datetime
fl_sales['Transaction Date'] = fl_sales['Transaction Date'].dt.to_period('M')                       # Remove day from the transaction date

fl_revenue = fl_sales.groupby('Transaction Date')[['Sale Amount']].sum().reset_index()              # Displays and groups by transaction date, finding the sum of each month, reset index for cleaner display

fl_revenue.rename(columns={'Transaction Date': 'Month', 'Sale Amount': 'Florida Revenue'}, inplace=True)    # Rename Columns

fl_revenue

      Month  Florida Revenue
0   2022-01         48143.95
1   2022-02         46257.35
2   2022-03         53541.25
3   2022-04         49505.25
4   2022-05         58326.64
5   2022-06         48683.24
6   2022-07         57545.77
7   2022-08         48656.98
8   2022-09         42839.10
9   2022-10         49508.42
10  2022-11         44519.86
11  2022-12         50885.58
12  2023-01         70589.71
13  2023-02         74547.62
14  2023-03         71490.80
15  2023-04         71671.43
16  2023-05         76942.62
17  2023-06         75958.75
18  2023-07         74438.54
19  2023-08         71626.47
20  2023-09         86388.39
21  2023-10         76570.52
22  2023-11         81150.82
23  2023-12         85799.00
24  2024-01         83362.33
25  2024-02         65035.27
26  2024-03         73851.01
27  2024-04         74763.04
28  2024-05         78325.77
29  2024-06         72071.52
30  2024-07         71626.47
31  2024-08         90013.08
32  2024-09         72945.83
33  2024-10         83388.68
34  2024-11         83561.14
35  2024-12         70589.71
36  2025-01        118654.88
37  2025-02        105056.57
38  2025-03        108664.43
39  2025-04        117732.51
40  2025-05        125169.68
41  2025-06        101328.59
42  2025-07        137940.05
43  2025-08        129936.53
44  2025-09        106935.33
45  2025-10        188215.96
46  2025-11        133022.84
47  2025-12        122408.27

South Carolina Monthly Revenue:

In [ ]:
sc_sales = ssales[ssales['Store ID'].isin(sc_ids)]                                                 # Use isin to filter store sales from previous South Carolina stores dataframe

sc_sales['Transaction Date'] = pd.to_datetime(sc_sales['Transaction Date'])                        # Convert Transaction Date to datetime
sc_sales['Transaction Date'] = sc_sales['Transaction Date'].dt.to_period('M')                      # Remove day from the transaction date

sc_revenue = sc_sales.groupby('Transaction Date')[['Sale Amount']].sum().reset_index()             # Displays and groups by transaction date, finding the sum of each month, reset index for cleaner display

sc_revenue.rename(columns={'Transaction Date': 'Month', 'Sale Amount': 'South Carolina Revenue'}, inplace=True)   # Rename Columns


sc_revenue

      Month  South Carolina Revenue
0   2022-01                 9640.38
1   2022-02                 9763.98
2   2022-03                 8366.63
3   2022-04                 8929.63
4   2022-05                 5396.03
5   2022-06                 7196.23
6   2022-07                13083.78
7   2022-08                 8916.43
8   2022-09                 8155.79
9   2022-10                10330.27
10  2022-11                 8355.29
11  2022-12                 8360.87
12  2023-01                13558.82
13  2023-02                14067.77
14  2023-03                13635.31
15  2023-04                 9587.55
16  2023-05                10674.71
17  2023-06                 9332.28
18  2023-07                10441.57
19  2023-08                12616.78
20  2023-09                10502.52
21  2023-10                18688.18
22  2023-11                10414.83
23  2023-12                12742.44
24  2024-01                15392.13
25  2024-02                13574.66
26  2024-03                 9646.93
27  2024-04                10615.33
28  2024-05                 9641.91
29  2024-06                10131.94
30  2024-07                12616.78
31  2024-08                10524.22
32  2024-09                18666.48
33  2024-10                10622.68
34  2024-11                12534.59
35  2024-12                13558.82
36  2025-01                20427.40
37  2025-02                16483.87
38  2025-03                19779.93
39  2025-04                19849.82
40  2025-05                15173.90
41  2025-06                15465.18
42  2025-07                21980.16
43  2025-08                34374.68
44  2025-09                16497.17
45  2025-10                27491.79
46  2025-11                18497.16
47  2025-12                22506.96

### Store performance ranked

### Top customers in each territory

### Number of transactions by product category, and total sales revenue per month by category

### **My Recommendation**